Upgrade path to Pydantic 2.0
whythawk/full-stack-fastapi-postgresql pull request #35
Opened 2023-07-25 07:34 UTC by turukawa

Major path updates include:

- frontend:
  - Node 16 to 18
  - Latest Pinia requires changes in `stores`, where imports are not required, and parameter declaration must happen in functions.
- backend and celeryworker:
  - Python 3.9 to 3.11
  - Poetry to Hatch
  - Postgres 14 to 15

2023-07-25 09:39 UTC, turukawa commented
The fix to `frontend` is related to a Vite error: https://github.com/scj2000/scj2000-web-v2/commit/b923143c106e352954771e19053d8eaddb414dbe

2023-07-29 22:00 UTC, br3ndonland requested changes
Thanks @turukawa. Great to see Hatch and inboard put to good use here. I have a few suggestions. Feel free to let me know if any further clarifications or changes are needed.

2023-08-08 15:12 UTC, turukawa commented on {{cookiecutter.project_slug}}/backend/backend.dockerfile
> +COPY ./app/pyproject.toml ./app/README.md ./app/__version__.py /app/
Does this last line of the script achieve that? 
`COPY ./app/ /app/`
It won't be needed during build so it doesn't really matter where it happens, and this way nothing else above effects it until it's copied in last...

2023-08-08 15:13 UTC, turukawa commented on {{cookiecutter.project_slug}}/backend/backend.dockerfile
>  RUN pip install --upgrade setuptools
Ah, ok ... I was finding that something was removing `setuptools` and then causing hell to break lose when it's needed later. So this is just forcing it.

2023-08-11 09:16 UTC, merged